### ISSUE TITLE
code release request

### ISSUE THREAD

**Issue by dihuangcode** [alcor-lab/MotionPrimitives#1]
Hi, 
will you release your motion primitive generating code in the feature? 
Thanks a lot

**Comment by dihuangcode** [comment]
@mdouskos @mario-gianni @martasn @MotionPrimitives

**Comment by dihuangcode** [comment]
waiting for reply

**Comment by mdouskos** [comment]
Dear @dihuangcode, apologies for the late reply. Thank you for your interest in our work. We plan to release the code sometime in the near future, stay tuned.

**Comment by deborapereira** [comment]
Hi,
interesting work, congrats; are you still planning to release the code that generates the motion primitives? It would be really useful to apply it to other datasets.
Thank you.
